# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoTrimDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoTrimDemo
	pod 'ICGVideoTrimmer'
  pod 'Masonry'
  pod 'ReactiveObjC'

  target 'VideoTrimDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VideoTrimDemoUITests' do
    # Pods for testing
  end

end
